

config: &config
  working_directory: /app
  docker:
    - image: google/cloud-sdk:167.0.0-alpine

decrypt: &decrypt_creds
  name: Decrypt creds
  command: |
      echo $GCP_KEY > key.enc
      base64 -d key.enc > ~/key.json
      gcloud auth activate-service-account --key-file ~/key.json

install_docker: &install_docker
  name: Install Docker client
  command: |
      set -x
      VER="17.03.0-ce"
      curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      mv /tmp/docker/* /usr/bin

build_backend_and_push: &build_backend_and_push
  name: Build Container
  command: |
      TAG=0.1.$CIRCLE_SHA1
      IMAGE=miris/nrtree
      docker build -t $IMAGE -f infra/Dockerfile .
      docker tag $IMAGE us.gcr.io/$MIRIS_GCP_PROJECT/$IMAGE:$TAG
      docker tag $IMAGE us.gcr.io/$MIRIS_GCP_PROJECT/$IMAGE:latest
      gcloud docker -- push us.gcr.io/$MIRIS_GCP_PROJECT/$IMAGE

deploy: &deploy
  name: Deploy to Container Engine
  command: |
      if [ $CIRCLE_BRANCH == "master" ]
      then
        gcloud components install kubectl
        gcloud config set project $MIRIS_GCP_PROJECT
        gcloud config set compute/zone us-west1-a
        gcloud container clusters get-credentials miris
        find ./infra -type f -exec sed -i -e "s|##version##|0.1.$CIRCLE_SHA1|g" {} \;
        find ./infra -type f -exec sed -i -e "s|##project##|$MIRIS_GCP_PROJECT|g" {} \;
        kubectl apply -f infra/k8s/v1/
      else
        echo Not on master -- skipping deploy
      fi

version: 2.0
jobs:
  setup:
    docker:
      - image: alpine
    working_directory: /app
    steps:
      - run: echo "just running"
  build-backend:
    << : *config
    steps:
      - checkout
      - run: *decrypt_creds
      - setup_remote_docker
      - run: *install_docker
      - run: *build_backend_and_push
  deploy:
    << : *config
    steps:
      - checkout
      - run: *decrypt_creds
      - run: *deploy

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - setup
      - build-backend:
          requires:
            - setup
          context: org-global
      #- deploy:
      #    requires:
      #      - build-backend
context: org-global