---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nrtree-deployment
  labels:
    app: nrtree
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nrtree
  template:
    metadata:
      labels:
        app: nrtree
    spec:
      containers:
        - name: nrtree
          image: us.gcr.io/##project##/miris/nrtree:##version##
          volumeMounts:
          - name: secrets
            mountPath: "/data"
            readOnly: true
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1

      volumes:
      - name: secrets
        secret:
          secretName: miris-nrtree-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nrtree-service
  namespace: default
  labels:
    app: nrtree
spec:
  type: NodePort
  selector:
    app: nrtree
  ports:
    - port: 80
      name: http
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nrtree-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: nrtree.miris.io
    http:
      paths:
      - backend:
          serviceName: nrtree-service
          servicePort: 80
